name: Build
on:
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Read VERSION file
        id: getversion
        run: |
          echo "::set-output name=version::$(cat VERSION)"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          file-version: ${{ steps.getversion.outputs.version }}
          product-version: ${{ steps.getversion.outputs.version }}
          output-file: "MultiTool v${{ steps.getversion.outputs.version }}.exe"
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: build/*.exe