name: Release
on:
    push:
        tags: [v*.*]
    workflow_dispatch:
permissions:
  contents: write
  packages: read
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Read VERSION file
        id: getversion
        run: |
          echo "::set-output name=version::$(cat VERSION)"
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
          cache: 'pip'
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          file-version: ${{ steps.getversion.outputs.version }}
          product-version: ${{ steps.getversion.outputs.version }}
          output-file: "MultiTool v${{ steps.getversion.outputs.version }}.exe"
      - name: "Upload Release"
        uses: ncipollo/release-action@v1
        with:
          name: MultiTool v1.1
          tag: v${{ steps.getversion.outputs.version }}
          artifacts: build/*.exe
